project:
  type: website

website:
  favicon: favicon.ico
  navbar:
    left:
      - text: "kquant"
        href: index.ipynb
      - text: "튜토리얼"
        href: tutorials/tutorial_index.ipynb
      - text: "API 참조문서"
        href: apiref/index.html
        target: _blank

format:
  html:
    theme: cosmo
    css: contents/styles.css
    toc: true
