project:
  type: website

website:
  favicon: favicon.ico
  navbar:
    left:
      - text: "kquant"
        href: index.ipynb
      - text: "튜토리얼"
        menu:
          - tutorials/tutorial_index.ipynb
          - tutorials/tutorial01.ipynb
          - tutorials/tutorial02.ipynb
          - tutorials/tutorial03.ipynb
          - tutorials/tutorial04.ipynb
      - text: "API 참조문서"
        href: apiref/index.html
        target: _blank
  comments:
    giscus:
      repo: koscom/kquant
      language: ko
      category: kquant
      reactions-enabled: false
format:
  html:
    theme: cosmo
    css: contents/styles.css
    toc: true
